version: '3.6'
services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "15672:5672"

  qq_fastapi:
    build: .
    image: qqimage
    volumes:
      - ./:/code
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    environment:
      - QQE_BROKER_HOST=rabbitmq

  qq_celery_worker:
    image: qqimage
    volumes:
      - ./:/code
    stdin_open: true
    tty: true
    command: /code/cworker.sh
    environment:
      - QQE_BROKER_HOST=rabbitmq
